services:
  - type: web
    name: social-network
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project4.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: social_network_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: false

databases:
  - name: social_network_db
    databaseName: social_network
    user: social_network
    plan: free
