# Generated by Django 5.0.4 on 2024-04-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_user_bio_user_birth_date_user_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
