# Generated by Django 5.1.3 on 2024-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_post_date_posted_post_date_updated_post_saves_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
